import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync('apps-script/ScreeningScoringV3.gs','utf8');
const cfg=fs.readFileSync('apps-script/ScreeningScoringConfigV3.gs','utf8');
const ids=['geral','tdah','bipolar','borderline','narcisismo','impulsividade','esquemas','modos','necessidades','codependencia','icaps','humor','ansiedade','autoestima','risco'];
for(const id of ids) assert.ok(new RegExp(`${id}:\\s*score`, 'i').test(src),`scorer ausente ${id}`);
assert.match(src,/DESCRIPTIVE_ONLY/);
assert.match(src,/STANDARD_BIS11/);
assert.match(src,/STANDARD_BDI2/);
assert.match(src,/STANDARD_HAMA_ADAPTED_SELF_REPORT/);
assert.match(src,/STANDARD_RSES_BR/);
assert.match(src,/SOURCE_DERIVED_CURRENT_HIGH_STAKES/);
assert.ok(!/percentileRank|percentile\s*=|simulatedPercentile/i.test(src),'não restaurar percentil simulado');
assert.ok(!/Quadro Clínico Mais Provável|diagnóstico provável/i.test(src),'scorer não pode emitir diagnóstico');
assert.match(src,/SCREENING_SCHEMAS_CONFIG_V3/);
assert.match(cfg,/const SCREENING_SCHEMAS_CONFIG_V3/);
assert.equal((cfg.match(/schemaId/g)||[]).length,108,'mapeamento Esquemas deve conter 108 itens');
assert.match(src,/CRITICAL_ITEM_4/);
assert.match(src,/SUICIDE_ITEM_ENDORSED/);
assert.match(src,/SUICIDAL_IDEATION_PRESENT/);
console.log('SCREENING_SCORING_V3_STATIC_PASS');
