import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync('apps-script/ScreeningPipelineV3.gs','utf8');
const expected=['SUBMITTED','VALIDATED','SCORED','REPORT_GENERATED','EMAIL_SENT','COMPLETE'];
const statesMatch=src.match(/STATES:\s*Object\.freeze\(\[([\s\S]*?)\]\)/);
assert.ok(statesMatch,'estados do pipeline ausentes');
const states=statesMatch[1];
for(const s of expected) assert.ok(states.includes(`'${s}'`),`estado ausente: ${s}`);
assert.ok(!states.includes('TRELLO_UPDATED'),'Trello não integra o pipeline clínico');
assert.ok(!states.includes('GPS_NOTIFIED'),'GPS não integra o pipeline clínico');
assert.match(src,/SCREENING_LEDGER_SHEET_ID/);
assert.match(src,/screeningSubmissionRef_/);
assert.match(src,/PIPELINE_STATE_JUMP/);
assert.match(src,/state\.status==='EMAIL_SENT'[\s\S]*'COMPLETE'/,'COMPLETE deve ocorrer depois do envio de e-mail');
const headersMatch=src.match(/HEADERS:\s*Object\.freeze\(\[([\s\S]*?)\]\)/);
assert.ok(headersMatch,'headers do ledger ausentes');
const headers=headersMatch[1].toUpperCase();
for(const forbidden of ['NAME','PATIENT','ANSWER','SCORE','DIAGNOS','HTML','REPORT_BODY','GPS','TRELLO']) assert.ok(!headers.includes(forbidden),`ledger atual não pode conter ${forbidden}`);
assert.match(src,/SCREENING_PIPELINE_LEGACY_HEADERS/,'migração não destrutiva do ledger legado deve permanecer até o primeiro uso da versão limpa');
console.log('SCREENING_PIPELINE_V3_STATIC_PASS');
